[package]
edition = "2024"
name = "bevy_sims"
version = "0.1.0"

[dependencies]
bevy = {version = "0.16", features = ["dynamic_linking", "shader_format_glsl"]}

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
